# Generated by Django 5.0.2 on 2025-10-19 22:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('export_type', models.CharField(choices=[('with-credentials', 'With Credentials'), ('without-credentials', 'Without Credentials'), ('template', 'Template')], default='template', max_length=20)),
                ('nodes', models.JSONField(default=list)),
                ('edges', models.JSONField(default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('import_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-exported_at'],
                'indexes': [models.Index(fields=['export_type'], name='workflows_e_export__9f5afa_idx'), models.Index(fields=['is_public'], name='workflows_e_is_publ_264850_idx'), models.Index(fields=['category'], name='workflows_e_categor_0639b6_idx')],
            },
        ),
    ]
